### ISSUE TITLE
Extend export of results to OEDB

### ISSUE THREAD

**Issue by gplssm** [openego/ding0#209]
## Problem description

We need a data export of Ding0's grid topology in a tabular format suitable to export to CSV files and to database tables of the OEDB.

## Table structure

_please fill the remaining tables based on the attributes used by [the eDisGo importer](https://github.com/openego/eDisGo/blob/2edc6f6c0fbadd72b1011376fe11bf4ef3b5158e/edisgo/data/import_data.py#L81-#L338)_
**LVGrid & MVGrid**

| Ding0 attribute | Attribute name |
| ------------------ | ------------------ |
| id_db | id |
| geo_data  | geom |
| (zensus_sum) population | population | %219
| v_level | voltage_nom |
| network | network |
| () lv_grid | ()  grid | %%123

**(MV loads) & LV Loads**

| Ding0 attribute | Attribute name |
| --------------- | -------------- |
| id_db | id |
| geo_data | geom |
| (grid) lv_grid | grid |
| consumption | consumption |

**MV Generators & LV Generators** 

| Ding0 attribute | Attribute name |
| --------------- | -------------- |
| id_db | id |
| geo_data | geom |
| capacity | nominal_capacity |
| type | type |
| subtype | subtype |
| v_level | v_level |
| (grid) lv_grid | grid |

**(MV) + LV BranchTees (Cable distributor)**

| Ding0 attribute | Attribute name |
| --------------- | -------------- |
| id_db | id |
| geo_data | geom |
| (grid) lv_grid | grid |
| (False) in_building | in_building | 

**MV Lines & LV Lines** 

| Ding0 attribute | Attribute name |
| --------------- | -------------- |
| id_db | id |
| type | type |
| length /1e3 | length |
| () kind | () kind |
| (grid) lv_grid | grid |

**LVLoadAreaCentreDing0**

_these are very special. In the end, a table detailing aggregated generation capacity within aggregated load areas (LAs) cumulated by generation voltage_level (6 or 7), type and subtype would be useful. Loads in aggregated LAs should grouped by sector._

Aggregated LV load areas/ LVLoadAreaCentreDing0 contain load and generators in in LV level that are modeled as "aggr. components" in eDisGo be connecting the right to the HV/MV substation's bus bar.  This is done cumulatively per sector for loads. Generators are aggregated by voltage level (6 or 7), its type and subtype.
Hence, to keep this procedure aggregation with the new, tabular data export format aggregation has to be performed while exporting data. Thus, the tables MV generators, MV loads and MV lines have to be extended by these aggregated loads, generators and its connection lines.
How load and generation is aggregated during data import to eDisGo can be found [here](https://github.com/openego/eDisGo/blob/f24bf098effed7a0f8992b8b1c0a6863f859a243/edisgo/data/import_data.py#L358-#L517). This function is called in [line ](https://github.com/openego/eDisGo/blob/f24bf098effed7a0f8992b8b1c0a6863f859a243/edisgo/data/import_data.py#L249)

**MV Disconnecting points (Circuit breaker)**

| Ding0 attribute | Attribute name |
| --------------- | -------------- |
| id_db | id |
| geo_data | geom |
| status | state |
| grid | grid |

**MV stations & LV stations**

| Ding0 attribute | Attribute name |
| -------------------- | -------------------- |
| id_db | id |
| geo_data | geom |
| () None | () grid |
| () grid | () mv_grid |

**MV + LV transformers**

| Ding0 attribute | Attribute name |
| -------------------- | -------------------- |
| id_db | id |
| count | count |
| geo_data | geom |
| grid | mv_grid |
| (grid) None | grid |
| v_level | voltage_op |
| s_max_a | (s) S_nom |
| x | (x) X |
| r | (r) R |

## Tasks

- [x] Complete table structure overview above. Required attributes for each component can be found in [the eDisGo importer](https://github.com/openego/eDisGo/blob/2edc6f6c0fbadd72b1011376fe11bf4ef3b5158e/edisgo/data/import_data.py#L81-#L338)
- [x] Complete [export function](https://github.com/openego/ding0/blob/25611ac8d0e9f82294fdaa485a69957cfecb1860/ding0/tools/results.py#L1401-#L1631) (be aware its located in the branch 'features/export-stats') according to defined table structure
- [x] Make sure references between individual tables can be build (i.e. transformers in stations, generators in grid, etc.)
- [x] Write function to export to CSV files
- [x] Include `run_id` in data export to distinguish from different runs
- [x] Write function to export tabular data to OEDB. Therefore, see [this function](https://github.com/openego/dingo/blob/670cb40982bb218497fbf460a1d703db16664a80/dingo/core/__init__.py#L1222-#L1337)) to see how export to OEDB works in general

**Comment by ingaloeser** [comment]
Some attributes had different names for LV and MV, e.g. grid. I put the MV name in brackets. Is it possible, that some attributes were omitted for the MV definition or did I misunderstand it?

**Comment by mltja** [comment]
Reopen if needed after discussion in #384
