### ISSUE TITLE
Stable grids results from Ding0

### ISSUE THREAD

**Issue by gplssm** [openego/ding0#251]
This issue coordinates subtasks to achieve stable grids resulting from a Ding0. "Stable" refers to grids that do not exceed their hosting capacity and do not violate operational constraints like voltage band and line loading.

## Problem description
When analyzing grid reinforcement needs with eDisGo, voltage at some nodes exceeds +/-10 % of nominal voltage which leads to identified grid reinforcement needs.

The investigation is done using grid 1882 of Ding0 data version 20180219182404.

## Tasks

- [ ] Why is Ding0 allowed to generate grids that violate operational constraints?
- [ ] Write script that analysis how many lines/nodes are affected by operational constraints violations. Use tabular files _ding0_grids__0_to_3608_{lv,mv}_crit_edges.csv_ and _ding0_grids__0_to_3608_{lv,mv}_crit_nodes.csv_
- [ ] Find out if voltage violations occur in MV level as well

## Notes

Operational constraints regarding voltage are differently defined in Ding0 and eDisGo. Whereas eDisGo simply requires no exceedance of +/-10 % of nominal voltage, Ding0 splits MV and LV level and thus applies strong limits for each grid level which makes sure +/- 10 % is not violated.

**Voltage limits Ding0**

Grid level | Load case | Feed-in case
-------------|--------------|------------------
 MV| 5 %  | 2 % 
 LV| 5 % | 3 % 

##  See also

* [eDisGo #80](https://github.com/openego/eDisGo/issues/80)

**Comment by mltja** [comment]
Discuss if reinforcement should be done in ding0 with edisgo functions and use the working and tested functions of @openego/edisgo . Or the currently not working reinforcement methods in ding0 should be repaired, and we want that time consuming double work.
