### ISSUE TITLE
Python 3.4 installation issue Travis

### ISSUE THREAD

**Issue by AnyaHe** [openego/ding0#314]
Tests in Travis fail for python version 3.4 due to installation problems (see [Travis run #372](https://travis-ci.org/openego/ding0/builds/591394793?utm_source=github_status&utm_medium=notification) ).

**Comment by gplssm** [comment]
Today, in a face-to-face discussion, @AnyaHe, @birgits and @gplssm decided to remove Python 3.4 as supported version.

## Todos

- [ ] Update [setup.py](https://github.com/openego/ding0/blob/330fef2fd394b1c28d5d34adceec0616ee35ef22/setup.py#L81-L82)
- [ ] Remove Python 3.4 from [travis file](https://github.com/openego/ding0/blob/330fef2fd394b1c28d5d34adceec0616ee35ef22/.travis.yml)
- [ ] Maybe: Add support for Python 3.7 (if it's easy)
