### ISSUE TITLE
Python 3.8 is not supported

### ISSUE THREAD

**Issue by gplssm** [openego/ding0#325]
Requirements:

## Critical

- [x] Tests fixed (smaller updates, some reference files recreated due to format changes introduced by io-packages, e.g. nx)
- [x] Update of pandas' DatetimeIndex
- [x] Migrated from geopy's vincenty() to distance()
- [x] Packages updated
- [x] Further minor adjustments
- [x] Test for isomorphism fails #341
- [x] Set package versions

## Warnings

- [x] Adjustments due to pyproj update #343
- [x] pandas: `FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
    from pandas.util.testing import assert_frame_equal`
- [x] `FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.`
- [ ] pypsa: `FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead`
- [ ] pypsa: `DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.`
- [ ] pypsa: `DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.`
- [ ] imp: `DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses`
- [ ] sqlalchemy: `SAWarning: Ignoring declarative-like tuple value of attribute 'segment': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?`
- [ ] pytest: `PytestUnknownMarkWarning: Unknown pytest.mark.dependency - is this a typo?  You can register custom marks to avoid this warning`

## Final steps

- [x] Tests passing
- [ ] ~travis file includes new python versions~ Dropped in favor of #338
- [x] SPDX classifier update
- [x] Test whether installation from scratch works properly
- [x] Bump version no
- [x] Update whatsnew

Finally: make new release!

**Comment by nesnoj** [comment]
@gplssm With py3.8 and the [recent packages](https://github.com/openego/ding0/blob/a4294bae262058ee77fde664eb63ab3c53ec1f36/requirements.txt) it seems to work fine (some tests are still running, though).

The only packages with version limits are `ego.io` (explicit commit) and `sqlalachemy` (due to oedialect incompatibility). Shall we set versions for the other packages too? For at least some packages I'd not expect newer versions since py3.8 is not the latest python version. But it may help to avoid problems in the future.

**Comment by nesnoj** [comment]
As the tests seem to be sensitive to package versions, I'll restrict them.
