### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by mltja** [openego/ding0#383]
Documentation parts:

Theoretical background: Grid generation
- [ ] MV grid generation #397 
- [ ] LV grid generation #398

Other
- [ ] Installation manual
- [ ] Add docstring for power flow worst-case cases or maybe link to @openego/edisgo ? #95
- [ ] Allocation of generators
- [ ] Documentation for handling and using the config #184
- [ ] Add changelog file #372 
- [ ] ...
